### ISSUE TITLE
Please release 0.7.6

### ISSUE THREAD

**Issue by MeggyCal** [MycroftAI/mycroft-skills-manager#42]
Version 0.7.6 is already available on PyPi, whereas on GitHub there is 0.7.5 latest. Could you please export a GitHub release tarball?

Why I want the tarball: I want to launch tests and you do not export the tests on PyPi.

**Comment by forslund** [comment]
Release tag added. Sorry for the delay.

**Comment by MeggyCal** [comment]
Thank you very much.
