### ISSUE TITLE
Please tag new releases also on github

### ISSUE THREAD

**Issue by MeggyCal** [MycroftAI/mycroft-skills-manager#53]
I can see many closed issues relevant to this one... when you bump version number on PyPi, could you please also tag it on GitHub? This time I am interested in 0.8.2 release.

**Comment by forslund** [comment]
Sorry slipped my mind (again). 0.8.2 is now tagged.

**Comment by MeggyCal** [comment]
Thanks a lot!

**Comment by forslund** [comment]
One of these days I need to write a script to do it for me so I don't forget!
