### ISSUE TITLE
MSM Creates too many threads

### ISSUE THREAD

**Issue by pedrocolon93** [MycroftAI/mycroft-skills-manager#8]
Usually in a normalish environment it is OK to create as many threads as you need, but in a raspberry pi with little memory, creating the 100 thread threadpool/putting all the threads to work leaves the system without memory.  I just propose we limit the threads to something reasonable (maybe 2-4).  I'll test this out on my machine and see what happens.  

`   def apply(self, func, skills):
        """Run a function on all skills in parallel"""

        def run_item(skill):
            try:
                func(skill)
                return True
            except MsmException as e:
                LOG.error('Error running {} on {}: {}'.format(
                    func.__name__, skill.name, repr(e)
                ))
                return False
            except:
                LOG.exception('Error running {} on {}:'.format(
                    func.__name__, skill.name
                ))

        with ThreadPool(100<--- change this to something more reasonable I understand that you want parallelism, but it becomes too memory demanding!) as tp:
return all(tp.map(run_item, skills))
`

**Comment by MatthewScholefield** [comment]
What about something in between like 20? Doing 2-4 significantly slows it down because there are a bunch of network calls that can be parallelized.

**Comment by penrods** [comment]
@pedrocolon93 Are you seeing actual performance issues? I don't on my Pi, so I'm curious what you are experiencing.  I agree that 2-4 threads is probably too limiting for this, but something like 20 seems like a reasonable threshold.

**Comment by pedrocolon93** [comment]
Sorry for the veeery delayed response, but in mine it just consumes all possible memory for reasons I don't know apart from just too many threads.  Cap it to 20 in the meanwhile.

**Comment by gras64** [comment]
you can not do that on the device selection in the config, z.b. "Piycroft"? a raspberry will most likely be online all day as time does not really matter. I have a raspberry with kodi which is fast at the limit. In normal operation I have about 500 mb ram free.

**Comment by gras64** [comment]
is there now an idea or a solution my raspberry still starts to swap with every update and my picture on kodi freezes? I also have to admit that I have many skills installed.
