### ISSUE TITLE
Distribute license file

### ISSUE THREAD

**Issue by scarabeusiv** [MycroftAI/mycroft-skills-manager#9]
When downloading the released archive from pypi it does not contain license files. Please adjust Manifest file to have pypi consider the doc/license files...

**Comment by scarabeusiv** [comment]
Also distribution packagers would be really happy if you shipped also your tests in the pypi archive as we use them to verify the basic sanity of your package is still somewheat okay when we update the python stack.

**Comment by MatthewScholefield** [comment]
@scarabeusiv As for the tests, is placing them in the module enough or should it be an executable module? (We use pytest so there's no main written by default) Also, do you know of a way to ship tests without moving it into the module? It's nice having the parallel structure of two side by side folders.

**Comment by scarabeusiv** [comment]
No need for tweaking. We can execute them distribution wise directly using pytest too.

Usually you don't want to install them just have them present in the tarball and for that weaking of MANIFEST.in is quite enough.
